---
title: "Welcome  to A Tale of Two Cities"
author: "Sean Leggett"
date: "2023-04-27"
---

Welcome, to A Tale Of Two Cities. The red half of Liverpool and the blue half of Manchester. Apologies to Manchester United.

# Introduction
A couple of years ago, this information was collected and reviewed to answer two burning questions:

1. What was the financial impact of Manchester City being acquired by the sovereign wealth fund of Abu Dhabi?
2. We were also intrigued by Garth Southgate's complaints about not enough English players in the Premier League. Was there merit to this?

So, we set about collecting all the information we could from a variety of sources. You can review the detailed look at Liverpool vs Man City in the R Exploration page.

We created a dashboard to analyze world cup finalists and their leagues of origin.

The information here may be updated in the future but for now it includes World Cup data from USA 94 up to and including Russia 2018.

Liverpool and Manchester City data is from the 2007/2008 Premier League season up to and including the 2017/2018 season. Abu Dhabi United Group completed their acquisition of Manchester City in 2008.

We hope you enjoy.

# Findings
It will come as no surprise that there was a significant impact to Manchester City after Abu Dhabi United Group's takeover. Revenues in particular changed drastically. Some of this can be expected simply by regular participation in the Champions League with it's added game days and substantial television revenues. However, the largest change in revenues came from the "commercial" stream. By the 2010/2011 season Manchester City commercial revenue matched Liverpool's and thereafter outstripped Liverpool by significant margins. By the end of our analysis period Manchester City booked commercial revenue of 235.4 Million pounds to Liverpool's 151.3 Million pounds. Given the histories of the two teams this is somewhat surprising and could possibly be explained by other companies in the Abu Dhabi family paying favourable contracts for advertisements, etc. It could certainly also be that Manchester City hired smarter commercial directors. We leave conclusions to the accountants among us.

In terms of overall revenues, we see a similar pattern with Manchester City passing Liverpool's revenues in 2010/2011 and culminating in a difference of 503.51 Million pounds to 455.1 Million pounds by the 2018/2019 season.

How this money was deployed is also interesting. The R Exploration page on this site looks at many aspects of player transfers. Clearly, Manchester City spend vast sums over the initial years of the new ownership to build a higher quality team. This also leads to higher wages which passed Liverpool's wage spending in the 2009/2010 season. However, players are not the only source of wages and Manchester City clearly invested across the entire spectrum of employees whether front/back office, coaching and training and commercial functions. One might say it is a very well run organization with solid plans.... and a lot of money.

In terms of Mr. Southgate complaining about needing more English players in the Premier League, our finding is that this is bollocks. If we assume that the goal is to win a world cup, then between USA 94 up to and including Russia 2018, of the players would participated in a world cup final:

1. 55% played their club football in their home country.
2. Of those who actually started a world cup final, 22% played their club football in their home country.
3. Of those teams that actually WON a world cup final, 31% played their club football in their home country.
4. Of those players who actually started AND won a world cup final, 12% played their club football in their home country.
5. The Premier League provides only the 4th most players to have participated in a final during this period being surpassed by Serie A, La Liga and Bundesliga.

So, perhaps the real challenge for the England team is better coaching, tactics and development of players rather than moaning about jobs for friends.

